config/routes.rb
TryTesting::Application.routes.draw do
  resources :mangments

end

app/models/mangment.rb
class Mangment < ActiveRecord::Base
  attr_accessible :age, :description, :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/mangments_controller.rb
class MangmentsController < ApplicationController
  # GET /mangments
  # GET /mangments.json
  def index
    @mangments = Mangment.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @mangments }
    end
  end

  # GET /mangments/1
  # GET /mangments/1.json
  def show
    @mangment = Mangment.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @mangment }
    end
  end

  # GET /mangments/new
  # GET /mangments/new.json
  def new
    @mangment = Mangment.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @mangment }
    end
  end

  # GET /mangments/1/edit
  def edit
    @mangment = Mangment.find(params[:id])
  end

  # POST /mangments
  # POST /mangments.json
  def create
    @mangment = Mangment.new(params[:mangment])

    respond_to do |format|
      if @mangment.save
        format.html { redirect_to @mangment, notice: 'Mangment was successfully created.' }
        format.json { render json: @mangment, status: :created, location: @mangment }
      else
        format.html { render action: "new" }
        format.json { render json: @mangment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /mangments/1
  # PUT /mangments/1.json
  def update
    @mangment = Mangment.find(params[:id])

    respond_to do |format|
      if @mangment.update_attributes(params[:mangment])
        format.html { redirect_to @mangment, notice: 'Mangment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @mangment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mangments/1
  # DELETE /mangments/1.json
  def destroy
    @mangment = Mangment.find(params[:id])
    @mangment.destroy

    respond_to do |format|
      format.html { redirect_to mangments_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/mangments_helper.rb
module MangmentsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TryTesting</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/mangments/_form.html.erb
<%= form_for(@mangment) do |f| %>
  <% if @mangment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@mangment.errors.count, "error") %> prohibited this mangment from being saved:</h2>

      <ul>
      <% @mangment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :age %><br />
    <%= f.number_field :age %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/mangments/edit.html.erb
<h1>Editing mangment</h1>

<%= render 'form' %>

<%= link_to 'Show', @mangment %> |
<%= link_to 'Back', mangments_path %>

app/views/mangments/index.html.erb
<h1>Listing mangments</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Age</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @mangments.each do |mangment| %>
  <tr>
    <td><%= mangment.name %></td>
    <td><%= mangment.description %></td>
    <td><%= mangment.age %></td>
    <td><%= link_to 'Show', mangment %></td>
    <td><%= link_to 'Edit', edit_mangment_path(mangment) %></td>
    <td><%= link_to 'Destroy', mangment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Mangment', new_mangment_path %>

app/views/mangments/new.html.erb
<h1>New mangment</h1>

<%= render 'form' %>

<%= link_to 'Back', mangments_path %>

app/views/mangments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @mangment.name %>
</p>

<p>
  <b>Description:</b>
  <%= @mangment.description %>
</p>

<p>
  <b>Age:</b>
  <%= @mangment.age %>
</p>


<%= link_to 'Edit', edit_mangment_path(@mangment) %> |
<%= link_to 'Back', mangments_path %>